### ISSUE TITLE
Throws warning on windows 10 when launched.

### ISSUE THREAD

**Issue by wgaylord** [FabricMC/Matcher#2]
`WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.`

**Comment by Player3324** [comment]
This is a Java bug, see e.g. https://stackoverflow.com/questions/16428098/groovy-shell-warning-could-not-open-create-prefs-root-node

Using Java 9 should avoid this, otherwise the stackoverflow workaround can fix it with 8.

**Comment by wgaylord** [comment]
I am not updating till 9 unless Mojang can get MC to run on it. (And every other program it broke) Otherwise it causes way to many problems to be worth dealing with.

**Comment by modmuss50** [comment]
Minecraft runs on 8 through to 12. Other programs cannot really help you. 

Most IDEs allow you to use a separate version of java easily without needing to install it as the default one.
